// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udpPacket.proto
package org.nit.monitorserver.proto;

public final class UdpPacket {
  private UdpPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UDP_COMMUNCATE_PACKETOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UDP_COMMUNCATE_PACKET)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *时间戳信息 用于比对消息是否丢失
     * </pre>
     *
     * <code>required int64 timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    boolean hasTimeStamp();
    /**
     * <pre>
     *时间戳信息 用于比对消息是否丢失
     * </pre>
     *
     * <code>required int64 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    long getTimeStamp();

    /**
     * <pre>
     *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
     * </pre>
     *
     * <code>required int32 msgType = 2;</code>
     * @return Whether the msgType field is set.
     */
    boolean hasMsgType();
    /**
     * <pre>
     *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
     * </pre>
     *
     * <code>required int32 msgType = 2;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <pre>
     *数据总长
     * </pre>
     *
     * <code>required int32 totalLength = 3;</code>
     * @return Whether the totalLength field is set.
     */
    boolean hasTotalLength();
    /**
     * <pre>
     *数据总长
     * </pre>
     *
     * <code>required int32 totalLength = 3;</code>
     * @return The totalLength.
     */
    int getTotalLength();

    /**
     * <pre>
     *当前包长
     * </pre>
     *
     * <code>required int32 currLength = 4;</code>
     * @return Whether the currLength field is set.
     */
    boolean hasCurrLength();
    /**
     * <pre>
     *当前包长
     * </pre>
     *
     * <code>required int32 currLength = 4;</code>
     * @return The currLength.
     */
    int getCurrLength();

    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return Whether the ipAddr field is set.
     */
    boolean hasIpAddr();
    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return The ipAddr.
     */
    java.lang.String getIpAddr();
    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return The bytes for ipAddr.
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();

    /**
     * <pre>
     *目标机端口号
     * </pre>
     *
     * <code>optional int32 port = 6;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <pre>
     *目标机端口号
     * </pre>
     *
     * <code>optional int32 port = 6;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <pre>
     *分包编号
     * </pre>
     *
     * <code>optional int32 snNum = 7;</code>
     * @return Whether the snNum field is set.
     */
    boolean hasSnNum();
    /**
     * <pre>
     *分包编号
     * </pre>
     *
     * <code>optional int32 snNum = 7;</code>
     * @return The snNum.
     */
    int getSnNum();

    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return Whether the portname field is set.
     */
    boolean hasPortname();
    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return The portname.
     */
    java.lang.String getPortname();
    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return The bytes for portname.
     */
    com.google.protobuf.ByteString
        getPortnameBytes();

    /**
     * <pre>
     *发送的消息缓存
     * </pre>
     *
     * <code>optional bytes buffers = 9;</code>
     * @return Whether the buffers field is set.
     */
    boolean hasBuffers();
    /**
     * <pre>
     *发送的消息缓存
     * </pre>
     *
     * <code>optional bytes buffers = 9;</code>
     * @return The buffers.
     */
    com.google.protobuf.ByteString getBuffers();
  }
  /**
   * <pre>
   *数据通信交互消息格式
   * </pre>
   *
   * Protobuf type {@code UDP_COMMUNCATE_PACKET}
   */
  public static final class UDP_COMMUNCATE_PACKET extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UDP_COMMUNCATE_PACKET)
      UDP_COMMUNCATE_PACKETOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UDP_COMMUNCATE_PACKET.newBuilder() to construct.
    private UDP_COMMUNCATE_PACKET(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UDP_COMMUNCATE_PACKET() {
      ipAddr_ = "";
      portname_ = "";
      buffers_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UDP_COMMUNCATE_PACKET();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UDP_COMMUNCATE_PACKET(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              timeStamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              totalLength_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              currLength_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              ipAddr_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              port_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              snNum_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              portname_ = bs;
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              buffers_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UdpPacket.internal_static_UDP_COMMUNCATE_PACKET_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UdpPacket.internal_static_UDP_COMMUNCATE_PACKET_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UdpPacket.UDP_COMMUNCATE_PACKET.class, UdpPacket.UDP_COMMUNCATE_PACKET.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timeStamp_;
    /**
     * <pre>
     *时间戳信息 用于比对消息是否丢失
     * </pre>
     *
     * <code>required int64 timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    @java.lang.Override
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *时间戳信息 用于比对消息是否丢失
     * </pre>
     *
     * <code>required int64 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <pre>
     *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
     * </pre>
     *
     * <code>required int32 msgType = 2;</code>
     * @return Whether the msgType field is set.
     */
    @java.lang.Override
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
     * </pre>
     *
     * <code>required int32 msgType = 2;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public int getMsgType() {
      return msgType_;
    }

    public static final int TOTALLENGTH_FIELD_NUMBER = 3;
    private int totalLength_;
    /**
     * <pre>
     *数据总长
     * </pre>
     *
     * <code>required int32 totalLength = 3;</code>
     * @return Whether the totalLength field is set.
     */
    @java.lang.Override
    public boolean hasTotalLength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *数据总长
     * </pre>
     *
     * <code>required int32 totalLength = 3;</code>
     * @return The totalLength.
     */
    @java.lang.Override
    public int getTotalLength() {
      return totalLength_;
    }

    public static final int CURRLENGTH_FIELD_NUMBER = 4;
    private int currLength_;
    /**
     * <pre>
     *当前包长
     * </pre>
     *
     * <code>required int32 currLength = 4;</code>
     * @return Whether the currLength field is set.
     */
    @java.lang.Override
    public boolean hasCurrLength() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *当前包长
     * </pre>
     *
     * <code>required int32 currLength = 4;</code>
     * @return The currLength.
     */
    @java.lang.Override
    public int getCurrLength() {
      return currLength_;
    }

    public static final int IPADDR_FIELD_NUMBER = 5;
    private volatile java.lang.Object ipAddr_;
    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return Whether the ipAddr field is set.
     */
    @java.lang.Override
    public boolean hasIpAddr() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return The ipAddr.
     */
    @java.lang.Override
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *目标机IP地址
     * </pre>
     *
     * <code>optional string ipAddr = 5;</code>
     * @return The bytes for ipAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 6;
    private int port_;
    /**
     * <pre>
     *目标机端口号
     * </pre>
     *
     * <code>optional int32 port = 6;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *目标机端口号
     * </pre>
     *
     * <code>optional int32 port = 6;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int SNNUM_FIELD_NUMBER = 7;
    private int snNum_;
    /**
     * <pre>
     *分包编号
     * </pre>
     *
     * <code>optional int32 snNum = 7;</code>
     * @return Whether the snNum field is set.
     */
    @java.lang.Override
    public boolean hasSnNum() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *分包编号
     * </pre>
     *
     * <code>optional int32 snNum = 7;</code>
     * @return The snNum.
     */
    @java.lang.Override
    public int getSnNum() {
      return snNum_;
    }

    public static final int PORTNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object portname_;
    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return Whether the portname field is set.
     */
    @java.lang.Override
    public boolean hasPortname() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return The portname.
     */
    @java.lang.Override
    public java.lang.String getPortname() {
      java.lang.Object ref = portname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          portname_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *portname
     * </pre>
     *
     * <code>optional string portname = 8;</code>
     * @return The bytes for portname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPortnameBytes() {
      java.lang.Object ref = portname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUFFERS_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString buffers_;
    /**
     * <pre>
     *发送的消息缓存
     * </pre>
     *
     * <code>optional bytes buffers = 9;</code>
     * @return Whether the buffers field is set.
     */
    @java.lang.Override
    public boolean hasBuffers() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *发送的消息缓存
     * </pre>
     *
     * <code>optional bytes buffers = 9;</code>
     * @return The buffers.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBuffers() {
      return buffers_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, totalLength_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, currLength_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ipAddr_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, port_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, snNum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, portname_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBytes(9, buffers_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalLength_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, currLength_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ipAddr_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, port_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, snNum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, portname_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, buffers_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UdpPacket.UDP_COMMUNCATE_PACKET)) {
        return super.equals(obj);
      }
      UdpPacket.UDP_COMMUNCATE_PACKET other = (UdpPacket.UDP_COMMUNCATE_PACKET) obj;

      if (hasTimeStamp() != other.hasTimeStamp()) return false;
      if (hasTimeStamp()) {
        if (getTimeStamp()
            != other.getTimeStamp()) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (getMsgType()
            != other.getMsgType()) return false;
      }
      if (hasTotalLength() != other.hasTotalLength()) return false;
      if (hasTotalLength()) {
        if (getTotalLength()
            != other.getTotalLength()) return false;
      }
      if (hasCurrLength() != other.hasCurrLength()) return false;
      if (hasCurrLength()) {
        if (getCurrLength()
            != other.getCurrLength()) return false;
      }
      if (hasIpAddr() != other.hasIpAddr()) return false;
      if (hasIpAddr()) {
        if (!getIpAddr()
            .equals(other.getIpAddr())) return false;
      }
      if (hasPort() != other.hasPort()) return false;
      if (hasPort()) {
        if (getPort()
            != other.getPort()) return false;
      }
      if (hasSnNum() != other.hasSnNum()) return false;
      if (hasSnNum()) {
        if (getSnNum()
            != other.getSnNum()) return false;
      }
      if (hasPortname() != other.hasPortname()) return false;
      if (hasPortname()) {
        if (!getPortname()
            .equals(other.getPortname())) return false;
      }
      if (hasBuffers() != other.hasBuffers()) return false;
      if (hasBuffers()) {
        if (!getBuffers()
            .equals(other.getBuffers())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStamp());
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgType();
      }
      if (hasTotalLength()) {
        hash = (37 * hash) + TOTALLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getTotalLength();
      }
      if (hasCurrLength()) {
        hash = (37 * hash) + CURRLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getCurrLength();
      }
      if (hasIpAddr()) {
        hash = (37 * hash) + IPADDR_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddr().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasSnNum()) {
        hash = (37 * hash) + SNNUM_FIELD_NUMBER;
        hash = (53 * hash) + getSnNum();
      }
      if (hasPortname()) {
        hash = (37 * hash) + PORTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getPortname().hashCode();
      }
      if (hasBuffers()) {
        hash = (37 * hash) + BUFFERS_FIELD_NUMBER;
        hash = (53 * hash) + getBuffers().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UdpPacket.UDP_COMMUNCATE_PACKET parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UdpPacket.UDP_COMMUNCATE_PACKET prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *数据通信交互消息格式
     * </pre>
     *
     * Protobuf type {@code UDP_COMMUNCATE_PACKET}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UDP_COMMUNCATE_PACKET)
        UdpPacket.UDP_COMMUNCATE_PACKETOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UdpPacket.internal_static_UDP_COMMUNCATE_PACKET_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UdpPacket.internal_static_UDP_COMMUNCATE_PACKET_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UdpPacket.UDP_COMMUNCATE_PACKET.class, UdpPacket.UDP_COMMUNCATE_PACKET.Builder.class);
      }

      // Construct using UdpPacket.UDP_COMMUNCATE_PACKET.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        currLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        ipAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        snNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        portname_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        buffers_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UdpPacket.internal_static_UDP_COMMUNCATE_PACKET_descriptor;
      }

      @java.lang.Override
      public UdpPacket.UDP_COMMUNCATE_PACKET getDefaultInstanceForType() {
        return UdpPacket.UDP_COMMUNCATE_PACKET.getDefaultInstance();
      }

      @java.lang.Override
      public UdpPacket.UDP_COMMUNCATE_PACKET build() {
        UdpPacket.UDP_COMMUNCATE_PACKET result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UdpPacket.UDP_COMMUNCATE_PACKET buildPartial() {
        UdpPacket.UDP_COMMUNCATE_PACKET result = new UdpPacket.UDP_COMMUNCATE_PACKET(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timeStamp_ = timeStamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msgType_ = msgType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalLength_ = totalLength_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.currLength_ = currLength_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ipAddr_ = ipAddr_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.port_ = port_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.snNum_ = snNum_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.portname_ = portname_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.buffers_ = buffers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UdpPacket.UDP_COMMUNCATE_PACKET) {
          return mergeFrom((UdpPacket.UDP_COMMUNCATE_PACKET)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UdpPacket.UDP_COMMUNCATE_PACKET other) {
        if (other == UdpPacket.UDP_COMMUNCATE_PACKET.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasTotalLength()) {
          setTotalLength(other.getTotalLength());
        }
        if (other.hasCurrLength()) {
          setCurrLength(other.getCurrLength());
        }
        if (other.hasIpAddr()) {
          bitField0_ |= 0x00000010;
          ipAddr_ = other.ipAddr_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasSnNum()) {
          setSnNum(other.getSnNum());
        }
        if (other.hasPortname()) {
          bitField0_ |= 0x00000080;
          portname_ = other.portname_;
          onChanged();
        }
        if (other.hasBuffers()) {
          setBuffers(other.getBuffers());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        if (!hasTotalLength()) {
          return false;
        }
        if (!hasCurrLength()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UdpPacket.UDP_COMMUNCATE_PACKET parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UdpPacket.UDP_COMMUNCATE_PACKET) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timeStamp_ ;
      /**
       * <pre>
       *时间戳信息 用于比对消息是否丢失
       * </pre>
       *
       * <code>required int64 timeStamp = 1;</code>
       * @return Whether the timeStamp field is set.
       */
      @java.lang.Override
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *时间戳信息 用于比对消息是否丢失
       * </pre>
       *
       * <code>required int64 timeStamp = 1;</code>
       * @return The timeStamp.
       */
      @java.lang.Override
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *时间戳信息 用于比对消息是否丢失
       * </pre>
       *
       * <code>required int64 timeStamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳信息 用于比对消息是否丢失
       * </pre>
       *
       * <code>required int64 timeStamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
       * </pre>
       *
       * <code>required int32 msgType = 2;</code>
       * @return Whether the msgType field is set.
       */
      @java.lang.Override
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
       * </pre>
       *
       * <code>required int32 msgType = 2;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
       * </pre>
       *
       * <code>required int32 msgType = 2;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000002;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型  1：配置、获取、控制命令  2：回复确认  3：分析配置 4：分析结果 5：icd分析请求 6：icd解析结果
       * </pre>
       *
       * <code>required int32 msgType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int totalLength_ ;
      /**
       * <pre>
       *数据总长
       * </pre>
       *
       * <code>required int32 totalLength = 3;</code>
       * @return Whether the totalLength field is set.
       */
      @java.lang.Override
      public boolean hasTotalLength() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *数据总长
       * </pre>
       *
       * <code>required int32 totalLength = 3;</code>
       * @return The totalLength.
       */
      @java.lang.Override
      public int getTotalLength() {
        return totalLength_;
      }
      /**
       * <pre>
       *数据总长
       * </pre>
       *
       * <code>required int32 totalLength = 3;</code>
       * @param value The totalLength to set.
       * @return This builder for chaining.
       */
      public Builder setTotalLength(int value) {
        bitField0_ |= 0x00000004;
        totalLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据总长
       * </pre>
       *
       * <code>required int32 totalLength = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalLength_ = 0;
        onChanged();
        return this;
      }

      private int currLength_ ;
      /**
       * <pre>
       *当前包长
       * </pre>
       *
       * <code>required int32 currLength = 4;</code>
       * @return Whether the currLength field is set.
       */
      @java.lang.Override
      public boolean hasCurrLength() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *当前包长
       * </pre>
       *
       * <code>required int32 currLength = 4;</code>
       * @return The currLength.
       */
      @java.lang.Override
      public int getCurrLength() {
        return currLength_;
      }
      /**
       * <pre>
       *当前包长
       * </pre>
       *
       * <code>required int32 currLength = 4;</code>
       * @param value The currLength to set.
       * @return This builder for chaining.
       */
      public Builder setCurrLength(int value) {
        bitField0_ |= 0x00000008;
        currLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前包长
       * </pre>
       *
       * <code>required int32 currLength = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        currLength_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddr_ = "";
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @return Whether the ipAddr field is set.
       */
      public boolean hasIpAddr() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @return The ipAddr.
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @return The bytes for ipAddr.
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @param value The ipAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ipAddr_ = getDefaultInstance().getIpAddr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标机IP地址
       * </pre>
       *
       * <code>optional string ipAddr = 5;</code>
       * @param value The bytes for ipAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipAddr_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       *目标机端口号
       * </pre>
       *
       * <code>optional int32 port = 6;</code>
       * @return Whether the port field is set.
       */
      @java.lang.Override
      public boolean hasPort() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *目标机端口号
       * </pre>
       *
       * <code>optional int32 port = 6;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       *目标机端口号
       * </pre>
       *
       * <code>optional int32 port = 6;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000020;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标机端口号
       * </pre>
       *
       * <code>optional int32 port = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        port_ = 0;
        onChanged();
        return this;
      }

      private int snNum_ ;
      /**
       * <pre>
       *分包编号
       * </pre>
       *
       * <code>optional int32 snNum = 7;</code>
       * @return Whether the snNum field is set.
       */
      @java.lang.Override
      public boolean hasSnNum() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *分包编号
       * </pre>
       *
       * <code>optional int32 snNum = 7;</code>
       * @return The snNum.
       */
      @java.lang.Override
      public int getSnNum() {
        return snNum_;
      }
      /**
       * <pre>
       *分包编号
       * </pre>
       *
       * <code>optional int32 snNum = 7;</code>
       * @param value The snNum to set.
       * @return This builder for chaining.
       */
      public Builder setSnNum(int value) {
        bitField0_ |= 0x00000040;
        snNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分包编号
       * </pre>
       *
       * <code>optional int32 snNum = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSnNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        snNum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object portname_ = "";
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @return Whether the portname field is set.
       */
      public boolean hasPortname() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @return The portname.
       */
      public java.lang.String getPortname() {
        java.lang.Object ref = portname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            portname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @return The bytes for portname.
       */
      public com.google.protobuf.ByteString
          getPortnameBytes() {
        java.lang.Object ref = portname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          portname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @param value The portname to set.
       * @return This builder for chaining.
       */
      public Builder setPortname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        portname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPortname() {
        bitField0_ = (bitField0_ & ~0x00000080);
        portname_ = getDefaultInstance().getPortname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *portname
       * </pre>
       *
       * <code>optional string portname = 8;</code>
       * @param value The bytes for portname to set.
       * @return This builder for chaining.
       */
      public Builder setPortnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        portname_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString buffers_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *发送的消息缓存
       * </pre>
       *
       * <code>optional bytes buffers = 9;</code>
       * @return Whether the buffers field is set.
       */
      @java.lang.Override
      public boolean hasBuffers() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       *发送的消息缓存
       * </pre>
       *
       * <code>optional bytes buffers = 9;</code>
       * @return The buffers.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBuffers() {
        return buffers_;
      }
      /**
       * <pre>
       *发送的消息缓存
       * </pre>
       *
       * <code>optional bytes buffers = 9;</code>
       * @param value The buffers to set.
       * @return This builder for chaining.
       */
      public Builder setBuffers(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        buffers_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的消息缓存
       * </pre>
       *
       * <code>optional bytes buffers = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuffers() {
        bitField0_ = (bitField0_ & ~0x00000100);
        buffers_ = getDefaultInstance().getBuffers();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UDP_COMMUNCATE_PACKET)
    }

    // @@protoc_insertion_point(class_scope:UDP_COMMUNCATE_PACKET)
    private static final UdpPacket.UDP_COMMUNCATE_PACKET DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UdpPacket.UDP_COMMUNCATE_PACKET();
    }

    public static UdpPacket.UDP_COMMUNCATE_PACKET getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UDP_COMMUNCATE_PACKET>
        PARSER = new com.google.protobuf.AbstractParser<UDP_COMMUNCATE_PACKET>() {
      @java.lang.Override
      public UDP_COMMUNCATE_PACKET parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UDP_COMMUNCATE_PACKET(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UDP_COMMUNCATE_PACKET> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UDP_COMMUNCATE_PACKET> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UdpPacket.UDP_COMMUNCATE_PACKET getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UDP_COMMUNCATE_PACKET_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UDP_COMMUNCATE_PACKET_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017udpPacket.proto\"\264\001\n\025UDP_COMMUNCATE_PAC" +
      "KET\022\021\n\ttimeStamp\030\001 \002(\003\022\017\n\007msgType\030\002 \002(\005\022" +
      "\023\n\013totalLength\030\003 \002(\005\022\022\n\ncurrLength\030\004 \002(\005" +
      "\022\016\n\006ipAddr\030\005 \001(\t\022\014\n\004port\030\006 \001(\005\022\r\n\005snNum\030" +
      "\007 \001(\005\022\020\n\010portname\030\010 \001(\t\022\017\n\007buffers\030\t \001(\014"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UDP_COMMUNCATE_PACKET_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UDP_COMMUNCATE_PACKET_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UDP_COMMUNCATE_PACKET_descriptor,
        new java.lang.String[] { "TimeStamp", "MsgType", "TotalLength", "CurrLength", "IpAddr", "Port", "SnNum", "Portname", "Buffers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
